name: Publish package to GitHub Packages
on:
  push:
    branches: [main]

jobs:
  build:
    defaults:
      run:
        working-directory: ./core-lib
        shell: bash
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "pnpm"
          cache-dependency-path: ./core-lib/pnpm-lock.yaml
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Publish to registry
        run: pnpm publish --recursive --filter "@whiskey-platform/*" --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
